### ISSUE TITLE
Regression from v0.1.10 - 'nested' vars not being processed 

### ISSUE THREAD

**Issue by spacedawwwg** [Scrum/postcss-at-rules-variables#209]
In v0.1.10, you could use nested vars that would be parsed before being set to a mixin, e.g:

```CSS
:root {
  --original-var: 4px;
  --nested-var: calc(2 * var(--original-var));
}
.class-name {
  @mixin mixinName var(--nested-var);
}
```
nested var would be resolved in the mixin as `calc(2 * 4px)`

As of v2, this no longer works and is instead simply passed through as `calc(2 * var(--original-var))` (i.e not resolving the original var)
